/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.login;

import controllers.UsuarioController;
import controllers.factory.FabricaControllers;
import dto.usuarios.LoginDTO;
import dto.usuarios.UsuarioDTO;
import enums.Rol;
import excepciones.presentacion.ControllerException;
import frames.admin.MenuAdmin;
import frames.clientes.MenuCliente;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author jalt2
 */
public class PnlLogin extends javax.swing.JPanel {
    private final UsuarioController controlUsuario;
    private final FrmLogin frmLogin;
    /**
     * Creates new form PnlLogin
     * @param frmLogin
     */
    public PnlLogin(FrmLogin frmLogin) {
        initComponents();
        this.controlUsuario = FabricaControllers.getUsuarioController();
        this.frmLogin = frmLogin;
        configurarEnter();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void iniciarSesion(){
        try {
            String correo = txtCorreo.getText().trim();
            char[] passwordChars = txtPassword.getPassword();

            String password = new String(passwordChars);
            
            if (correo.trim().isEmpty() && password.trim().isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Rellene todos los campos para iniciar sesion.",
                        "Datos Faltantes",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }
            
            if (correo.trim().isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Ingrese un correo.",
                        "Dato Faltante",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }
            
            if (password.trim().isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Ingrese una contraseña.",
                        "Dato Faltante",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }

            LoginDTO usuarioLoginDTO = new LoginDTO(correo, password);

            UsuarioDTO usuarioLoggeado = controlUsuario.iniciarSesion(usuarioLoginDTO);
            
            
            Arrays.fill(passwordChars, '\0');
            
            JOptionPane.showMessageDialog(
                this,
                "Bienvenid@ " + usuarioLoggeado.getNombre()
            );
            
            //Si el usuario es un admin
            if (usuarioLoggeado.getRol() == Rol.ADMIN) {
                MenuAdmin menuAdmin = new MenuAdmin(usuarioLoggeado);
                menuAdmin.setVisible(true);
            }else if (usuarioLoggeado.getRol() == Rol.CLIENTE) {
                MenuCliente menuCliente = new MenuCliente(usuarioLoggeado);
                menuCliente.setVisible(true);
            }
            
            frmLogin.dispose();

        } catch (ControllerException e) {
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error",
                JOptionPane.INFORMATION_MESSAGE
            );
        }  
    }
    
    private void configurarEnter() {
        // Hace que ENTER ejecute el botón de login automáticamente
        javax.swing.SwingUtilities.invokeLater(() -> {
            java.awt.Container parent = this;

            while (parent != null && !(parent instanceof javax.swing.JRootPane)) {
                parent = parent.getParent();
            }

            if (parent instanceof javax.swing.JRootPane rootPane) {
                rootPane.setDefaultButton(btnIniciarSesion);
            }
        });
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenidoLogin = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        pnlContenidoLogin.setBackground(new java.awt.Color(9, 79, 138));
        pnlContenidoLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setText("INICIAR SESION");
        pnlContenidoLogin.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo:");
        pnlContenidoLogin.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 58, 87), 2));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        pnlContenidoLogin.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, 40));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña:");
        pnlContenidoLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 58, 87), 2));
        pnlContenidoLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 200, 40));

        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        btnIniciarSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIniciarSesionKeyPressed(evt);
            }
        });
        pnlContenidoLogin.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 170, 40));

        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarse.setText("REGISTRARSE");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        pnlContenidoLogin.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 170, 40));

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlContenidoLogin.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 710, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenidoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenidoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        iniciarSesion();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
        frmLogin.mostrarPanelRegistro();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        frmLogin.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIniciarSesionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel pnlContenidoLogin;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
