/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames.admin;

import controllers.factory.FabricaControllers;
import dto.usuarios.UsuarioDTO;
import enums.Rol;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author jalt2
 */
public class MenuAdmin extends javax.swing.JFrame {
    
    private final UsuarioDTO admin;
    
    /**
     * Creates new form MenuPrincipal
     * @param admin
     */
    public MenuAdmin(UsuarioDTO admin) {
        if (admin == null) {
            throw new IllegalArgumentException( "Administrador requerido");
        }

        if (admin.getRol() != Rol.ADMIN) {
            throw new IllegalArgumentException("Acceso no autorizado");
        }
        initComponents();
        this.setLocationRelativeTo(null);
        FabricaControllers.getPeliculaController();
        this.admin = admin;  
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMiPerfil = new javax.swing.JMenu();
        mnuPeliculas = new javax.swing.JMenu();
        mnuGestionPeliculas = new javax.swing.JMenuItem();
        mnuFunciones = new javax.swing.JMenu();
        mnuPagos = new javax.swing.JMenu();
        mnuBoletos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContenido.setBackground(new java.awt.Color(9, 79, 138));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Administrativo");
        pnlContenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        mnuMiPerfil.setText("Mi Perfil");
        jMenuBar1.add(mnuMiPerfil);

        mnuPeliculas.setText("Peliculas");

        mnuGestionPeliculas.setText("Gestionar Peliculas");
        mnuGestionPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionPeliculasActionPerformed(evt);
            }
        });
        mnuPeliculas.add(mnuGestionPeliculas);

        jMenuBar1.add(mnuPeliculas);

        mnuFunciones.setText("Funciones");
        jMenuBar1.add(mnuFunciones);

        mnuPagos.setText("Pagos");
        jMenuBar1.add(mnuPagos);

        mnuBoletos.setText("Boletos");
        jMenuBar1.add(mnuBoletos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGestionPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionPeliculasActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PnlPeliculas());
    }//GEN-LAST:event_mnuGestionPeliculasActionPerformed
    
    private void mostrarPanel(JPanel panel){
        pnlContenido.removeAll();
        
        pnlContenido.setLayout(new BorderLayout());
        
        pnlContenido.add(panel,BorderLayout.CENTER);
        
        pnlContenido.revalidate();
        
        pnlContenido.repaint();
        
        this.pack();
        
        this.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuBoletos;
    private javax.swing.JMenu mnuFunciones;
    private javax.swing.JMenuItem mnuGestionPeliculas;
    private javax.swing.JMenu mnuMiPerfil;
    private javax.swing.JMenu mnuPagos;
    private javax.swing.JMenu mnuPeliculas;
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
