/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.admin;

import controllers.UsuarioController;
import controllers.factory.FabricaControllers;
import dto.usuarios.UsuarioDTO;
import excepciones.presentacion.ControllerException;
import java.util.List;
import javax.swing.JOptionPane;
import tables.ModeloTablaUsuarios;

/**
 *
 * @author jalt2
 */
public class PnlGestionClientes extends javax.swing.JPanel {
    private final UsuarioController control;
    private UsuarioDTO cliente;
    private ModeloTablaUsuarios modeloTabla;
    
    /**
     * Creates new form PnlGestionClientes
     */
    public PnlGestionClientes() {
        initComponents();
        this.control = FabricaControllers.getUsuarioController();
        llenarTablaClientes();
    }
    
    private void llenarTablaClientes(){
        try {
            List<UsuarioDTO> usuarios = control.listarClientes();
        
            modeloTabla = new ModeloTablaUsuarios(usuarios);

            tblClientes.setModel(modeloTabla);
            
        } catch (ControllerException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }
    
    private void seleccionarCliente(){
        int filaSeleccionada = tblClientes.getSelectedRow();

        if (filaSeleccionada == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Debes seleccionar una película",
                    "Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        cliente = modeloTabla.obtenerUsuario(filaSeleccionada);
    }
    
    private void activarUsuario(){
        
        try {
            boolean activado = control.activarUsuario(cliente.getId());
            if (activado) {
                JOptionPane.showMessageDialog(this, "Usuario activado.");
                llenarTablaClientes();
            }
        } catch (ControllerException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );
        }
    }
    
    private void desactivarUsuario(){
        try {
            boolean desactivado = control.desactivarUsuarioAdmin(cliente.getId());
            
            if (desactivado) {
                JOptionPane.showMessageDialog(this, "Usuario desactivado.");
                llenarTablaClientes();
            }
        } catch (ControllerException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPeliculas = new javax.swing.JPanel();
        scrPane = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnActivarCliente = new javax.swing.JButton();
        btnDesactivarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFiltroNombre = new javax.swing.JTextField();

        pnlPeliculas.setBackground(new java.awt.Color(9, 79, 138));
        pnlPeliculas.setPreferredSize(new java.awt.Dimension(1200, 645));
        pnlPeliculas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        scrPane.setViewportView(tblClientes);

        pnlPeliculas.add(scrPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 1060, 470));

        btnActivarCliente.setBackground(new java.awt.Color(12, 93, 140));
        btnActivarCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnActivarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnActivarCliente.setText("ACTIVAR");
        btnActivarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarClienteActionPerformed(evt);
            }
        });
        pnlPeliculas.add(btnActivarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        btnDesactivarCliente.setBackground(new java.awt.Color(12, 93, 140));
        btnDesactivarCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDesactivarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnDesactivarCliente.setText("DESACTIVAR");
        btnDesactivarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarClienteActionPerformed(evt);
            }
        });
        pnlPeliculas.add(btnDesactivarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestionar Clientes");
        pnlPeliculas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filtrar por nombre:");
        pnlPeliculas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, -1));
        pnlPeliculas.add(txtFiltroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarClienteActionPerformed
        // TODO add your handling code here:
        activarUsuario();
    }//GEN-LAST:event_btnActivarClienteActionPerformed

    private void btnDesactivarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarClienteActionPerformed
        // TODO add your handling code here:
        desactivarUsuario();
    }//GEN-LAST:event_btnDesactivarClienteActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            seleccionarCliente();
        }
    }//GEN-LAST:event_tblClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarCliente;
    private javax.swing.JButton btnDesactivarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlPeliculas;
    private javax.swing.JScrollPane scrPane;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtFiltroNombre;
    // End of variables declaration//GEN-END:variables
}
