/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import controllers.PeliculaController;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import panels.PnlPeliculas;

/**
 *
 * @author jalt2
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    
    private final PeliculaController controlPelicula;
    
    /**
     * Creates new form MenuPrincipal
     * @param controlPelicula
     */
    public FrmMenuPrincipal(PeliculaController controlPelicula) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlPelicula = controlPelicula;
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMiPerfil = new javax.swing.JMenu();
        mnuPeliculas = new javax.swing.JMenu();
        mnuGestionPeliculas = new javax.swing.JMenuItem();
        mnuFunciones = new javax.swing.JMenu();
        mnuBoletos = new javax.swing.JMenu();
        mnuPagos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContenido.setBackground(new java.awt.Color(9, 79, 138));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("Menu Administrativo");
        pnlContenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        mnuMiPerfil.setText("Mi Perfil");
        jMenuBar1.add(mnuMiPerfil);

        mnuPeliculas.setText("Peliculas");

        mnuGestionPeliculas.setText("Gestionar Peliculas");
        mnuGestionPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionPeliculasActionPerformed(evt);
            }
        });
        mnuPeliculas.add(mnuGestionPeliculas);

        jMenuBar1.add(mnuPeliculas);

        mnuFunciones.setText("Funciones");
        jMenuBar1.add(mnuFunciones);

        mnuBoletos.setText("Boletos");
        jMenuBar1.add(mnuBoletos);

        mnuPagos.setText("Pagos");
        jMenuBar1.add(mnuPagos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGestionPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionPeliculasActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PnlPeliculas(this.controlPelicula));
    }//GEN-LAST:event_mnuGestionPeliculasActionPerformed
    
    private void mostrarPanel(JPanel panel){
        pnlContenido.removeAll();
        
        pnlContenido.setLayout(new BorderLayout());
        
        pnlContenido.add(panel,BorderLayout.CENTER);
        
        pnlContenido.revalidate();
        
        pnlContenido.repaint();
        
        this.pack();
        
        this.setLocationRelativeTo(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PeliculaController controller = new PeliculaController();
                new FrmMenuPrincipal(controller).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuBoletos;
    private javax.swing.JMenu mnuFunciones;
    private javax.swing.JMenuItem mnuGestionPeliculas;
    private javax.swing.JMenu mnuMiPerfil;
    private javax.swing.JMenu mnuPagos;
    private javax.swing.JMenu mnuPeliculas;
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
