/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frames.clientes;

import controllers.BoletoController;
import controllers.SalaController;
import controllers.factory.FabricaControllers;
import dto.funciones.FuncionDTO;
import dto.salas.AsientoDTO;
import dto.usuarios.UsuarioDTO;
import dtos.boletos.BoletoDTO;
import excepciones.presentacion.ControllerException;
import java.awt.Frame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import tables.ModeloTablaAsientos;

/**
 *
 * @author jalt2
 */
public class DialogSeleccionarAsiento extends javax.swing.JDialog {
    private final SalaController salaControl;
    private final BoletoController boletoControl;
    private final FuncionDTO funcionSeleccionada;
    private AsientoDTO asientoSeleccionado;
    private BoletoDTO boletoGenerado;
    private ModeloTablaAsientos modelo;
    private final UsuarioDTO cliente;
    private List<AsientoDTO> asientos;
    /**
     * Creates new form DialogSeleccionarAsiento
     * @param parent
     * @param funcionSeleccionada
     * @param modal
     * @param cliente
     */
    public DialogSeleccionarAsiento(java.awt.Frame parent, boolean modal,FuncionDTO funcionSeleccionada,UsuarioDTO cliente) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.salaControl = FabricaControllers.getSalaController();
        this.boletoControl = FabricaControllers.getBoletoController();
        this.funcionSeleccionada = funcionSeleccionada;
        
        llenarTablaAsientos();
        this.cliente = cliente;
        
    }
    
    private void llenarTablaAsientos(){
        try {
            asientos = salaControl.listarAsientosDisponibles(funcionSeleccionada.getNumSala());
            
            modelo = new ModeloTablaAsientos(asientos);
            
            tblAsientos.setModel(modelo);
        } catch (ControllerException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );
        }
    }
    
    private void seleccionarAsiento() {
        
        int filaSeleccionada = tblAsientos.getSelectedRow();

        if (filaSeleccionada == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Debes seleccionar un asiento",
                    "Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }
        
        

        asientoSeleccionado = modelo.obtenerAsiento(filaSeleccionada);
        
        try {
            salaControl.reservarAsiento(funcionSeleccionada, asientoSeleccionado);
        } catch (ControllerException ex) {
            Logger.getLogger(DialogSeleccionarAsiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        try {
            this.boletoGenerado = boletoControl.reservarAsiento(cliente.getId(), funcionSeleccionada.getId(), asientoSeleccionado);
        } catch (ControllerException ex) {
            Logger.getLogger(DialogConfirmarBoleto.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
    }
    
    private void abrirDialogBoleto(){
        DialogConfirmarBoleto dialog = new DialogConfirmarBoleto(
                (Frame) SwingUtilities.getWindowAncestor(this),
                true,
                this.funcionSeleccionada,
                this.asientoSeleccionado,
                cliente,
                boletoGenerado
            );
        
        dialog.setVisible(true);
        BoletoDTO boleto = dialog.getBoletoGenerado();
        

        if (boleto != null) {
            this.boletoGenerado = boleto;
        }
    }

    public BoletoDTO getBoletoGenerado() {
        return boletoGenerado;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAsiento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsientos = new javax.swing.JTable();
        lblFiltrar = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(9, 79, 138));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAsiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAsiento.setForeground(new java.awt.Color(255, 255, 255));
        lblAsiento.setText("Seleccione un asiento:");
        jPanel1.add(lblAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 36, -1, -1));

        tblAsientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAsientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAsientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAsientos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 680, 450));

        lblFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        lblFiltrar.setText("Filtrar por fila:");
        jPanel1.add(lblFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, 30));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una fila", "A", "B", "C", "D", "E", "F", "G", "H" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAsientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAsientosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            seleccionarAsiento();
            abrirDialogBoleto();
            
        }
    }//GEN-LAST:event_tblAsientosMouseClicked

    public AsientoDTO getAsientoSeleccionado() {
        return asientoSeleccionado;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsiento;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JTable tblAsientos;
    // End of variables declaration//GEN-END:variables
}
