/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frames.clientes;

import controllers.BoletoController;
import controllers.factory.FabricaControllers;
import dto.funciones.FuncionDTO;
import dto.salas.AsientoDTO;
import dto.usuarios.UsuarioDTO;
import dtos.boletos.BoletoDTO;

/**
 *
 * @author jalt2
 */
public class DialogConfirmarBoleto extends javax.swing.JDialog {

    private final FuncionDTO funcionSeleccionada;
    private final BoletoController controlBoleto;
    private BoletoDTO boletoGenerado;
    private final AsientoDTO asientoSeleccionado;
    private final UsuarioDTO cliente;

    /**
     * Creates new form DialogConfirmarBoleto
     * @param parent
     * @param modal
     * @param funcionSeleccionada
     * @param asientoSeleccionado
     * @param cliente
     * @param boletoGenerado
     */
    public DialogConfirmarBoleto(java.awt.Frame parent, boolean modal,FuncionDTO funcionSeleccionada,AsientoDTO asientoSeleccionado,UsuarioDTO cliente,BoletoDTO boletoGenerado) {
        super(parent, modal);
        initComponents();
        this.controlBoleto = FabricaControllers.getBoletoController();
        this.cliente = cliente;
        this.funcionSeleccionada = funcionSeleccionada;
        this.asientoSeleccionado = asientoSeleccionado;
        this.boletoGenerado = boletoGenerado;
        
        llenarCamposBoleto();
        
        
    }

    public BoletoDTO getBoletoGenerado() {
        return boletoGenerado;
    }
    
    
    private void llenarCamposBoleto(){
        this.txtPelicula.setText(funcionSeleccionada.getTituloPelicula());
        this.dateFecha.setDate(funcionSeleccionada.getFecha());
        this.timeHora.setTime(funcionSeleccionada.getHora());
        this.txtSala.setText(funcionSeleccionada.getNumSala().toString());
        this.txtAsiento.setText(asientoSeleccionado.getFila()+asientoSeleccionado.getNumero().toString());
        this.txtPrecio.setText(boletoGenerado.getPrecio().toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAsiento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPelicula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateFecha = new com.github.lgooddatepicker.components.DatePicker();
        jLabel3 = new javax.swing.JLabel();
        timeHora = new com.github.lgooddatepicker.components.TimePicker();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();
        txtAsiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnProcederPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(9, 79, 138));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAsiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAsiento.setForeground(new java.awt.Color(255, 255, 255));
        lblAsiento.setText("Confirme su boleto");
        jPanel1.add(lblAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 36, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pelicula:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel1.add(txtPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));
        jPanel1.add(dateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 220, 30));

        jLabel3.setText("Hora:");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));
        jPanel1.add(timeHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 220, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sala:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Asiento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        jPanel1.add(txtSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 210, 30));
        jPanel1.add(txtAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 210, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 210, 30));

        btnProcederPago.setBackground(new java.awt.Color(12, 93, 140));
        btnProcederPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProcederPago.setForeground(new java.awt.Color(255, 255, 255));
        btnProcederPago.setText("PROCEDER AL PAGO");
        jPanel1.add(btnProcederPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcederPago;
    private com.github.lgooddatepicker.components.DatePicker dateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAsiento;
    private com.github.lgooddatepicker.components.TimePicker timeHora;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtPelicula;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSala;
    // End of variables declaration//GEN-END:variables
}
