/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frames.clientes;

import controllers.FuncionController;
import controllers.factory.FabricaControllers;
import dto.funciones.FuncionDTO;
import dto.salas.AsientoDTO;
import dto.usuarios.UsuarioDTO;
import dtos.PeliculaDTO;
import excepciones.presentacion.ControllerException;
import java.awt.Frame;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import tables.ModeloTablaFuncionesPeliculas;

/**
 *
 * @author jalt2
 */
public class DialogSeleccionarFuncion extends javax.swing.JDialog {
    private FuncionDTO funcionSeleccionada;
    private ModeloTablaFuncionesPeliculas modelo;
    private final PeliculaDTO peliculaSeleccionada;
    private AsientoDTO asientoSeleccionado;
    private final FuncionController control;
    private final UsuarioDTO cliente;
    /**
     * Creates new form DialogSeleccionarFuncion
     * @param parent
     * @param modal
     * @param peliculaSeleccionada
     * @param cliente
     */
    public DialogSeleccionarFuncion(java.awt.Frame parent, boolean modal, PeliculaDTO peliculaSeleccionada,UsuarioDTO cliente) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.cliente = cliente;
        this.control = FabricaControllers.getFuncionController();
        this.peliculaSeleccionada = peliculaSeleccionada;
        this.lblPelicula.setText("Funciones para "+this.peliculaSeleccionada.getTitulo());
        this.dateFuncion.setDate(LocalDate.now());
        llenarTablaFuncionesPelicula();
        
        
    }
    
    private void llenarTablaFuncionesPelicula(){
        
        try {
            List<FuncionDTO> peliculas = control.buscarFuncionesPorPelicula(peliculaSeleccionada.getId());
            
            modelo = new ModeloTablaFuncionesPeliculas(peliculas);
            
            tblFunciones.setModel(modelo);
        } catch (ControllerException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );
        }
    }
    
    private void seleccionarFuncion() {
        
        int filaSeleccionada = tblFunciones.getSelectedRow();

        if (filaSeleccionada == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Debes seleccionar una funcion",
                    "Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        funcionSeleccionada = modelo.obtenerFuncion(filaSeleccionada);

        dispose();
    }
    
    private void filtrarFuncionesFecha(){
        LocalDate fechaFuncion = dateFuncion.getDate();
        try {
            List<FuncionDTO> peliculasPorFecha = control.buscarFuncionesPorPeliculaYFecha(peliculaSeleccionada.getId(),fechaFuncion);
            
            modelo = new ModeloTablaFuncionesPeliculas(peliculasPorFecha);
            
            tblFunciones.setModel(modelo);
        } catch (ControllerException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );
        }
    }
    
    private void abrirDialogAsientos() {

        DialogSeleccionarAsiento dialog = new DialogSeleccionarAsiento(
                (Frame) SwingUtilities.getWindowAncestor(this),
                true,
                this,
                this.funcionSeleccionada,
                cliente
            );
        
        dialog.setVisible(true);
        AsientoDTO asiento = dialog.getAsientoSeleccionado();

        if (asiento != null) {
            this.asientoSeleccionado = asiento;
        }
    }

    public FuncionDTO getFuncionSeleccionada() {
        return funcionSeleccionada;
    }

    public AsientoDTO getAsientoSeleccionado() {
        return asientoSeleccionado;
    }

    public void setAsientoSeleccionado(AsientoDTO asientoSeleccionado) {
        this.asientoSeleccionado = asientoSeleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        lblPelicula = new javax.swing.JLabel();
        scrPanel = new javax.swing.JScrollPane();
        tblFunciones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dateFuncion = new com.github.lgooddatepicker.components.DatePicker();
        btnFiltrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlContenido.setBackground(new java.awt.Color(9, 79, 138));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPelicula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblPelicula.setText("Funciones para");
        pnlContenido.add(lblPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        tblFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblFunciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionesMouseClicked(evt);
            }
        });
        scrPanel.setViewportView(tblFunciones);

        pnlContenido.add(scrPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 700, 410));

        jLabel2.setText("Filtrar por fecha");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        pnlContenido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));
        pnlContenido.add(dateFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, 30));

        btnFiltrar.setText("FILTRAR");
        btnFiltrar.setBackground(new java.awt.Color(12, 93, 140));
        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        pnlContenido.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 90, 30));

        btnVolver.setBackground(new java.awt.Color(255, 51, 51));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlContenido.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 80, 30));

        btnMostrarTodos.setBackground(new java.awt.Color(12, 93, 140));
        btnMostrarTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarTodos.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarTodos.setText("MOSTRAR TODOS");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });
        pnlContenido.add(btnMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione una funcion:");
        pnlContenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFuncionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionesMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            seleccionarFuncion();
            abrirDialogAsientos();
        }
    }//GEN-LAST:event_tblFuncionesMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        filtrarFuncionesFecha();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        // TODO add your handling code here:
        llenarTablaFuncionesPelicula();
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnVolver;
    private com.github.lgooddatepicker.components.DatePicker dateFuncion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JScrollPane scrPanel;
    private javax.swing.JTable tblFunciones;
    // End of variables declaration//GEN-END:variables
}
