/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frames.clientes;

import controllers.BoletoController;
import controllers.factory.FabricaControllers;
import dtos.boletos.BoletoDTO;
import dtos.boletos.PagoDTO;
import enums.EstadoPago;
import enums.MetodoPago;
import excepciones.presentacion.ControllerException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jalt2
 */
public class DialogPago extends javax.swing.JDialog {

    private final DialogConfirmarBoleto dialogAnt;

    private final BoletoDTO boletoGenerado;
    private final BoletoController controlBoleto;

    /**
     * Creates new form DialogPago
     * @param parent
     * @param modal
     * @param dialogAnt
     * @param boletoGenerado
     */
    public DialogPago(java.awt.Frame parent, boolean modal,DialogConfirmarBoleto dialogAnt,BoletoDTO boletoGenerado) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.dialogAnt = dialogAnt;
        this.boletoGenerado = boletoGenerado;
        this.controlBoleto = FabricaControllers.getBoletoController();
        llenarCampos();
    }
    
    private void llenarCampos(){
        txtMonto.setText(boletoGenerado.getPrecio().toString());
        
    }
    
    private void pagar(){
        Double monto = Double.valueOf(txtMonto.getText());
        MetodoPago metodoPago = MetodoPago.valueOf(cmbMetodoPago.getSelectedItem().toString());
        
        if (cmbMetodoPago.getSelectedIndex()==0) {
            
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un metodo de pago.",
                    "Error",
                    JOptionPane.WARNING_MESSAGE
            );  
            return;
            
        }
        
        PagoDTO pagDTO = new PagoDTO(boletoGenerado.getId(), monto, metodoPago, EstadoPago.PAGADO, LocalDate.now());
        
        try {
            controlBoleto.confirmarPago(boletoGenerado.getId(), pagDTO);
            JOptionPane.showMessageDialog(this, "Pago realizado correctamente.");
        } catch (ControllerException ex) {
            Logger.getLogger(DialogPago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumTarjeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        dateExpiracion = new com.github.lgooddatepicker.components.DatePicker();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(9, 79, 138));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Metodo de Pago:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setText("Numero de tarjeta:");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtNumTarjeta.setEnabled(false);
        jPanel1.add(txtNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 240, 30));

        jLabel3.setText("CVV:");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        txtCVV.setEnabled(false);
        jPanel1.add(txtCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 130, 30));

        dateExpiracion.setEnabled(false);
        jPanel1.add(dateExpiracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 30));

        jLabel4.setText("Fecha expiracion:");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Monto: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtMonto.setEditable(false);
        txtMonto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMonto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMonto.setEnabled(false);
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, 30));

        btnPagar.setText("PAGAR");
        btnPagar.setBackground(new java.awt.Color(12, 93, 140));
        btnPagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 150, 30));

        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar metodo de pago", "EFECTIVO", "TARJETA", "TRANSFERENCIA" }));
        cmbMetodoPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbMetodoPago.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cmbMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, 30));

        btnVolver.setBackground(new java.awt.Color(255, 51, 51));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        pagar();
        dispose();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        dialogAnt.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbMetodoPago;
    private com.github.lgooddatepicker.components.DatePicker dateExpiracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumTarjeta;
    // End of variables declaration//GEN-END:variables
}
