/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames.clientes;

import dto.usuarios.UsuarioDTO;
import enums.Rol;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author jalt2
 */
public class MenuCliente extends javax.swing.JFrame {
    private final UsuarioDTO cliente;
    /**
     * Creates new form MenuCliente
     * @param cliente
     */
    public MenuCliente(UsuarioDTO cliente) {
        if (cliente == null) {
            throw new IllegalArgumentException( "Cliente requerido");
        }

        if (cliente.getRol() != Rol.CLIENTE) {
            throw new IllegalArgumentException("Inicie sesion como cliente para continuar");
        }        
        initComponents();
        this.setLocationRelativeTo(null);
        this.cliente = cliente;
        this.lblBienvenido.setText("Bienvenido " + cliente.getNombre());
        
    }
    
    private void mostrarPanel(JPanel panel){
        pnlContenido.removeAll();
        
        pnlContenido.setLayout(new BorderLayout());
        
        pnlContenido.add(panel,BorderLayout.CENTER);
        
        pnlContenido.revalidate();
        
        pnlContenido.repaint();
        
        this.pack();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPanel = new javax.swing.JScrollPane();
        pnlContenido = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        mnuBar = new javax.swing.JMenuBar();
        mnuMiPerfil = new javax.swing.JMenu();
        btnMiPerfil = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrPanel.setBackground(new java.awt.Color(9, 79, 138));

        pnlContenido.setBackground(new java.awt.Color(9, 79, 138));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("Bienvenido");
        pnlContenido.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        scrPanel.setViewportView(pnlContenido);

        mnuMiPerfil.setText("Mi Perfil");

        btnMiPerfil.setText("Perfil");
        btnMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiPerfilActionPerformed(evt);
            }
        });
        mnuMiPerfil.add(btnMiPerfil);

        mnuBar.add(mnuMiPerfil);

        jMenu2.setText("Peliculas");
        mnuBar.add(jMenu2);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiPerfilActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new PnlMiPerfil(cliente));
    }//GEN-LAST:event_btnMiPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnMiPerfil;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuMiPerfil;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JScrollPane scrPanel;
    // End of variables declaration//GEN-END:variables
}
