/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames.clientes;

import controllers.UsuarioController;
import controllers.factory.FabricaControllers;
import dto.usuarios.UsuarioDTO;
import enums.Rol;
import excepciones.presentacion.ControllerException;
import frames.login.FrmLogin;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author jalt2
 */
public class MenuCliente extends javax.swing.JFrame {
    private UsuarioDTO cliente;
    private CardLayout cardLayout;
    private PnlMiPerfil pnlMiPerfil;
    private PnlInicio pnlInicio;
    private final UsuarioController control;
    
    /**
     * Creates new form MenuCliente
     * @param cliente
     */
    public MenuCliente(UsuarioDTO cliente) {
        if (cliente == null) {
            throw new IllegalArgumentException( "Cliente requerido");
            
        }

        if (cliente.getRol() != Rol.CLIENTE) {
            throw new IllegalArgumentException("Inicie sesion como cliente para continuar");
        }        
        initComponents();
        this.setLocationRelativeTo(null);
        this.cliente = cliente;
        this.control = FabricaControllers.getUsuarioController();
        cardLayout = new CardLayout();
        pnlContenido.setLayout(cardLayout);
        inicializarPanels();
        
    }
    
    private void inicializarPanels() {
        cardLayout = new CardLayout();

        pnlContenido.setLayout(cardLayout);

        pnlInicio = new PnlInicio(cliente);

        pnlMiPerfil = new PnlMiPerfil(cliente);

        pnlContenido.add(pnlInicio, "INICIO");

        pnlContenido.add(pnlMiPerfil,"MI_PERFIL");

        mostrarInicio();
    }
    
    private void  mostrarInicio(){
        cardLayout.show(pnlContenido, "INICIO");
    }
    
    private void cerrarSesion(){
        int opcion = JOptionPane.showConfirmDialog(this,"¿Desea cerrar sesión?","Cerrar sesión",JOptionPane.YES_NO_OPTION);
        
        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }
        
        //Borrar usuarioLoggeado
        this.cliente = null;
        
        FrmLogin login = new FrmLogin();
        
        login.setVisible(true);
        
        this.dispose();
    }
    
    private String autenticarUsuario() {

        JPasswordField passwordField = new JPasswordField();

        int opcion = JOptionPane.showConfirmDialog(
                this,
                passwordField,
                "Ingrese su contraseña actual",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (opcion != JOptionPane.OK_OPTION) {
            return null;
        }

        String password = new String(passwordField.getPassword());

        if (password.trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "La contraseña es obligatoria.",
                    "Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return null;
        }

        return password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPanel = new javax.swing.JScrollPane();
        pnlContenido = new javax.swing.JPanel();
        mnuBar = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        btnIncio = new javax.swing.JMenuItem();
        btnDesactivarCuenta = new javax.swing.JMenuItem();
        mnuMiPerfil = new javax.swing.JMenu();
        btnMiPerfil = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnVerPeliculas = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrPanel.setBackground(new java.awt.Color(9, 79, 138));

        pnlContenido.setBackground(new java.awt.Color(9, 79, 138));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        scrPanel.setViewportView(pnlContenido);

        mnuInicio.setText("Inicio");

        btnIncio.setText("Volver al inicio");
        btnIncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncioActionPerformed(evt);
            }
        });
        mnuInicio.add(btnIncio);

        btnDesactivarCuenta.setText("Desactivar Cuenta");
        btnDesactivarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarCuentaActionPerformed(evt);
            }
        });
        mnuInicio.add(btnDesactivarCuenta);

        mnuBar.add(mnuInicio);

        mnuMiPerfil.setText("Mi Perfil");

        btnMiPerfil.setText("Perfil");
        btnMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiPerfilActionPerformed(evt);
            }
        });
        mnuMiPerfil.add(btnMiPerfil);

        mnuBar.add(mnuMiPerfil);

        jMenu2.setText("Peliculas");

        btnVerPeliculas.setText("Ver Peliculas");
        btnVerPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPeliculasActionPerformed(evt);
            }
        });
        jMenu2.add(btnVerPeliculas);

        mnuBar.add(jMenu2);

        mnuCerrarSesion.setText("Cerrar Sesion");

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        mnuCerrarSesion.add(btnCerrarSesion);

        mnuBar.add(mnuCerrarSesion);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiPerfilActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlContenido, "MI_PERFIL");
    }//GEN-LAST:event_btnMiPerfilActionPerformed

    private void btnIncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncioActionPerformed
        // TODO add your handling code here:
        mostrarInicio();
    }//GEN-LAST:event_btnIncioActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnDesactivarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarCuentaActionPerformed
        try {
            String passwordActual = autenticarUsuario();
            
            if (passwordActual==null) {
                return;
            }
            
            // TODO add your handling code here:
            boolean desactivado = control.desactivarUsuario(cliente.getId(),passwordActual);
            if (desactivado) {
                JOptionPane.showMessageDialog(this, "Cuenta desactivada, contactar un admin para reactivar.");

                this.cliente = null;

                FrmLogin login = new FrmLogin();

                login.setVisible(true);

                this.dispose();
            }
            
        } catch (ControllerException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnDesactivarCuentaActionPerformed

    private void btnVerPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerPeliculasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnDesactivarCuenta;
    private javax.swing.JMenuItem btnIncio;
    private javax.swing.JMenuItem btnMiPerfil;
    private javax.swing.JMenuItem btnVerPeliculas;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuCerrarSesion;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenu mnuMiPerfil;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JScrollPane scrPanel;
    // End of variables declaration//GEN-END:variables
}
