/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames.clientes;

import dto.usuarios.UsuarioDTO;
import enums.Rol;
import frames.login.FrmLogin;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author jalt2
 */
public class MenuCliente extends javax.swing.JFrame {
    private UsuarioDTO cliente;
    private CardLayout cardLayout;
    private PnlMiPerfil pnlMiPerfil;
    private PnlInicio pnlInicio;
    
    /**
     * Creates new form MenuCliente
     * @param cliente
     */
    public MenuCliente(UsuarioDTO cliente) {
        if (cliente == null) {
            throw new IllegalArgumentException( "Cliente requerido");
        }

        if (cliente.getRol() != Rol.CLIENTE) {
            throw new IllegalArgumentException("Inicie sesion como cliente para continuar");
        }        
        initComponents();
        this.setLocationRelativeTo(null);
        this.cliente = cliente;
        cardLayout = new CardLayout();
        pnlContenido.setLayout(cardLayout);
        inicializarPanels();
        
    }
    
    private void inicializarPanels() {
        cardLayout = new CardLayout();

        pnlContenido.setLayout(cardLayout);

        pnlInicio = new PnlInicio(cliente);

        pnlMiPerfil = new PnlMiPerfil(cliente);

        pnlContenido.add(pnlInicio, "INICIO");

        pnlContenido.add(pnlMiPerfil,"MI_PERFIL");

        mostrarInicio();
    }
    
    private void  mostrarInicio(){
        cardLayout.show(pnlContenido, "INICIO");
    }
    
    private void cerrarSesion(){
        int opcion = JOptionPane.showConfirmDialog(this,"¿Desea cerrar sesión?","Cerrar sesión",JOptionPane.YES_NO_OPTION);
        
        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }
        
        //Borrar usuarioLoggeado
        this.cliente = null;
        
        FrmLogin login = new FrmLogin();
        
        login.setVisible(true);
        
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPanel = new javax.swing.JScrollPane();
        pnlContenido = new javax.swing.JPanel();
        mnuBar = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        btnIncio = new javax.swing.JMenuItem();
        mnuMiPerfil = new javax.swing.JMenu();
        btnMiPerfil = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuCerrarSesion = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrPanel.setBackground(new java.awt.Color(9, 79, 138));

        pnlContenido.setBackground(new java.awt.Color(9, 79, 138));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        scrPanel.setViewportView(pnlContenido);

        mnuInicio.setText("Inicio");

        btnIncio.setText("Volver al inicio");
        btnIncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncioActionPerformed(evt);
            }
        });
        mnuInicio.add(btnIncio);

        mnuBar.add(mnuInicio);

        mnuMiPerfil.setText("Mi Perfil");

        btnMiPerfil.setText("Perfil");
        btnMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiPerfilActionPerformed(evt);
            }
        });
        mnuMiPerfil.add(btnMiPerfil);

        mnuBar.add(mnuMiPerfil);

        jMenu2.setText("Peliculas");
        mnuBar.add(jMenu2);

        mnuCerrarSesion.setText("Cerrar Sesion");

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        mnuCerrarSesion.add(btnCerrarSesion);

        mnuBar.add(mnuCerrarSesion);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiPerfilActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlContenido, "MI_PERFIL");
    }//GEN-LAST:event_btnMiPerfilActionPerformed

    private void btnIncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncioActionPerformed
        // TODO add your handling code here:
        mostrarInicio();
    }//GEN-LAST:event_btnIncioActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnIncio;
    private javax.swing.JMenuItem btnMiPerfil;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuCerrarSesion;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenu mnuMiPerfil;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JScrollPane scrPanel;
    // End of variables declaration//GEN-END:variables
}
