/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.clientes;

import controllers.UsuarioController;
import controllers.factory.FabricaControllers;
import dto.usuarios.UsuarioDTO;
import java.awt.BorderLayout;
import java.awt.Dimension;

/**
 *
 * @author jalt2
 */
public class PnlMiPerfil extends javax.swing.JPanel {
    private final UsuarioDTO cliente;
    private final UsuarioController control;
    
    /**
     * Creates new form PnlMiPerfil
     * @param cliente
     */
    public PnlMiPerfil(UsuarioDTO cliente) {
        initComponents();
        this.setPreferredSize(new Dimension(1250,683));
        this.setLayout(new BorderLayout());
        this.add(pnlMiPerfil, BorderLayout.CENTER);
        this.cliente = cliente;
        this.control = FabricaControllers.getUsuarioController();
        cargarCamposCliente();
        
    }
    
    private void cargarCamposCliente(){
        //Datos Personales
        txtNombre.setText(cliente.getNombre());
        txtApellidoMaterno.setText(cliente.getApellidoMaterno());
        txtApellidoPaterno.setText(cliente.getApellidoPaterno());
        fchNacimiento.setDate(cliente.getFechaNacimiento());
        txtTelefono.setText(cliente.getTelefono());
        
        //Datos Acceso
        txtEmail.setText(cliente.getEmail()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMiPerfil = new javax.swing.JPanel();
        pnlDatosPersonales = new javax.swing.JPanel();
        txtApellidoPaterno = new javax.swing.JTextField();
        lblApellidoPaterno = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        lblApellidoMaterno = new javax.swing.JLabel();
        fchNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        btnActualizarDatosPersonales = new javax.swing.JButton();
        pnlDatosAcesso = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblEmailNuevo = new javax.swing.JLabel();
        txtEmailNuevo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        pnlMiPerfil.setBackground(new java.awt.Color(9, 79, 138));
        pnlMiPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlDatosPersonales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellidoPaterno.setEnabled(false);
        pnlDatosPersonales.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 260, 30));

        lblApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoPaterno.setText("Apellido Paterno:");
        pnlDatosPersonales.add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        txtNombre.setEnabled(false);
        pnlDatosPersonales.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 30));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        pnlDatosPersonales.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtApellidoMaterno.setEnabled(false);
        pnlDatosPersonales.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 270, 30));

        lblApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoMaterno.setText("Apellido Materno:");
        pnlDatosPersonales.add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        fchNacimiento.setEnabled(false);
        pnlDatosPersonales.add(fchNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 260, 30));

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setText("Fecha Nacimiento:");
        pnlDatosPersonales.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        txtTelefono.setEnabled(false);
        pnlDatosPersonales.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 270, 30));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Telefono (10 digitos):");
        pnlDatosPersonales.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        btnActualizarDatosPersonales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarDatosPersonales.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarDatosPersonales.setText("Editar Datos Personales");
        pnlDatosPersonales.add(btnActualizarDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, 30));

        pnlMiPerfil.add(pnlDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 970, 330));

        pnlDatosAcesso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Acesso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlDatosAcesso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setEnabled(false);
        pnlDatosAcesso.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail:");
        pnlDatosAcesso.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtPassword.setEnabled(false);
        pnlDatosAcesso.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 280, 30));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña nueva:");
        pnlDatosAcesso.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar Correo");
        pnlDatosAcesso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cambiar Contraseña");
        pnlDatosAcesso.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, 30));

        lblEmailNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailNuevo.setText("E-mail nuevo:");
        pnlDatosAcesso.add(lblEmailNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        txtEmailNuevo.setEnabled(false);
        pnlDatosAcesso.add(txtEmailNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 260, 30));

        pnlMiPerfil.add(pnlDatosAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 970, 180));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mi Perfil");
        pnlMiPerfil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMiPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMiPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDatosPersonales;
    private com.github.lgooddatepicker.components.DatePicker fchNacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailNuevo;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlDatosAcesso;
    private javax.swing.JPanel pnlDatosPersonales;
    private javax.swing.JPanel pnlMiPerfil;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailNuevo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
